source $HOME/.config/nvim/plugins/plugins.vim
source $HOME/.config/nvim/settings/sets.vim
source $HOME/.config/nvim/settings/mappings.vim
source $HOME/.config/nvim/settings/paths.vim
source $HOME/.config/nvim/plug-config/dracula.vim
source $HOME/.config/nvim/plug-config/dashboard.vim
source $HOME/.config/nvim/plug-config/colorizer.lua
source $HOME/.config/nvim/plug-config/gitsigns.lua
source $HOME/.config/nvim/plug-config/treesitter.lua
source $HOME/.config/nvim/plug-config/telescope.lua
source $HOME/.config/nvim/plug-config/lualine.lua
source $HOME/.config/nvim/plug-config/bufferline.lua
"source $HOME/.config/nvim/themes/cyberpunk.vim
